### ISSUE TITLE
canedge_datasource_cli crashed on request

### ISSUE THREAD

**Issue by C31Cab514** [CSS-Electronics/canedge-grafana-backend#5]
We are running into an issue with the provided python code canedge_datasource_cli.py whiile trying to setup our test dashboard on Grafana. When grafana send a request to the server, it crashes with the following error

```
2023-02-13 18:49:37,432 - canedge_datasource - ERROR - Exception on /query [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/canedge-grafana-backend/canedge_datasource/query.py", line 130, in query_view
    return jsonify(query_cache(req_in))
  File "/usr/local/lib/python3.8/dist-packages/flask_caching/__init__.py", line 952, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/ubuntu/canedge-grafana-backend/canedge_datasource/query.py", line 117, in query_cache
    res = _query_time_series(req, start_date, stop_date)
  File "/home/ubuntu/canedge-grafana-backend/canedge_datasource/query.py", line 171, in _query_time_series
    return time_series_phy_data(fs=app.fs,
  File "/home/ubuntu/canedge-grafana-backend/canedge_datasource/signal.py", line 232, in time_series_phy_data
    start_epoch, df_raw_can, df_raw_lin = _load_log_file(fs, log_file, [x.itf for x in device_group], passwords)
  File "/home/ubuntu/canedge-grafana-backend/canedge_datasource/signal.py", line 363, in _load_log_file
    return _load_log_file_cache(file, itf_used, passwords)
  File "/usr/local/lib/python3.8/dist-packages/flask_caching/__init__.py", line 952, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/ubuntu/canedge-grafana-backend/canedge_datasource/signal.py", line 358, in _load_log_file_cache
    df_raw_can_local = mdf_file.get_data_frame() if CanedgeInterface.CAN in itf_used_in else pd.DataFrame()
RuntimeError: An unexpected error occurred while obtaining a CAN iterator: Not finalized?
```

Looking into grafana, the query that was send looks like the following:

`"{\"device\":\"XXXXXXXX\",\"itf\":\"CAN\",\"chn\":\"CH2\",\"db\":\"XXX can protocol XXXX v2_0\",\"signal\":\"acVoltageUV\"}"`

**Comment by MatinF** [comment]
It looks like you’re working with FW 01.07.01 log files but with an old repo/dependency set - please use the latest version and requirements and let us know if this solves it

**Comment by C31Cab514** [comment]
That solved the issue, thanks.
